WTE/WTE/urls.py
from django.contrib import admin
from django.urls import path,include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Wteapp.urls')),
    path('accounts/', include("accounts.urls")),
    

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

WTE/Wteapp/urls.py
from django.urls import path

from . import views



app_name = 'Wte_app'


urlpatterns = [
    path ('home/',views.home_Page,name='HomePage'),
    path("restaurant/add/", views.add_restaurant, name="add_restaurant"),
    path("restaurant/list/", views.list_restaurant, name="list_restaurant"),
    path("restaurant/detail/<res_id>/", views.restaurant_details, name="restaurant_details"),
    path("restaurant/delete/<res_id>/", views.delete_post, name="delete_post"),
    path("cafe/delete/<res_id>/", views.delete_cafe, name="delete_cafe"),
    path("cafe/add/", views.add_cafe, name="add_cafe"),
    path("cafe/list/", views.list_cafe, name="list_cafe"),
    path("cafe/detail/<cafe_id>/", views.cafe_details, name="cafe_details"),
    path("comment/<res_id>/", views.add_comment, name="comment"),
    path("comment/cafe/<cafe_id>/", views.add_comment_cafe, name="comments"),





]

WTE/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("register/", views.register_user, name="register_user"),
    path("login/", views.login_user, name="login_user"),
    path("logout/", views.logout_user, name="logout_user")
]

WTE/Wteapp/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class restaurant(models.Model):
    picture = models.ImageField(upload_to = "images/")
    name = models.CharField(max_length=2048)
    city = models.TextField()
    address = models.TextField()
    cuisine = models.TextField()
    description = models.TextField()
    work_time = models.TextField()
    menu = models.URLField()
    location = models.URLField()
    rating = models.FloatField()


class Comment(models.Model):
    user = models.ForeignKey(User,on_delete = models.CASCADE)
    post = models.ForeignKey(restaurant, on_delete = models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now=True)
    rating = models.FloatField()

class cafe(models.Model):
    picture = models.ImageField(upload_to = "images/")
    name = models.CharField(max_length=2048)
    city = models.TextField()
    address = models.TextField()
    cuisine = models.TextField()
    description = models.TextField()
    work_time = models.TextField()
    menu = models.URLField()
    location = models.URLField()
    rating = models.FloatField()

class CommentCafes(models.Model):
    user = models.ForeignKey(User,on_delete = models.CASCADE)
    post = models.ForeignKey(cafe, on_delete = models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now=True)
    rating = models.FloatField()

WTE/Wteapp/views.py
from django.shortcuts import render ,redirect
from django.http import HttpRequest,HttpResponse
from .models import restaurant ,Comment ,cafe ,User,CommentCafes
from django.db.models import Avg
from django.contrib.auth.decorators import login_required



# Create your views here.
def home_Page (request: HttpRequest) :
    return render (request , "Wteapp/base.html")



def add_restaurant(request : HttpRequest):

    if request.method == "POST":
        new_restaurant = restaurant(name=request.POST["name"], city = request.POST["city"], address=request.POST["address"], cuisine = request.POST.get('cuisine','international'), description =request.POST["description"] ,  work_time =request.POST["work_time"], picture=request.FILES.get('picture',False), location =request.POST["location"], menu=request.POST["menu"] , rating=request.POST["rating"])
        new_restaurant.save()

    return render(request, "Wteapp/Add_res.html", {"restaurants" : restaurant})


def list_restaurant(request: HttpRequest):
    
    
    if "search" in request.GET:
        view_restaurants = restaurant.objects.filter(name=request.GET["search"])
    else:
        view_restaurants = restaurant.objects.all()

 
    return render(request, "Wteapp/Res_list.html", {"restaurants" : view_restaurants})


def delete_post(request: HttpRequest, res_id:int):

    try:
        rest = restaurant.objects.get(id=res_id)
    except:
        return render(request , "Wteapp/not_found.html")

    rest.delete()

    return redirect ("Wte_app:list_restaurant")



def restaurant_details(request : HttpRequest, res_id : int):

    try:
        restaurants = restaurant.objects.get(id=res_id)
        comments = Comment.objects.filter(post = restaurants)
    except:
        return render(request , "Wteapp/not_found.html")

    average=Comment.objects.filter(post=restaurants).aggregate(Avg('rating'))
    
    return render(request, "Wteapp/view_Res.html", {"restaurant" : restaurants ,"comments" : comments ,"averages" : average })



def add_cafe(request : HttpRequest):

    if request.method == "POST":
        new_cafe = cafe(name=request.POST["name"], city = request.POST["city"], address=request.POST["address"], cuisine = request.POST.get('cuisine','international'), description =request.POST["description"] ,  work_time =request.POST["work_time"], picture=request.FILES.get('picture',False), location =request.POST["location"], menu=request.POST["menu"] , rating=request.POST["rating"])
        new_cafe.save()

    return render(request, "Wteapp/add_cafe.html", {"cafes" : cafe})

def list_cafe(request: HttpRequest):
    
    
    if "search" in request.GET:
        view_cafe = cafe.objects.filter(name=request.GET["search"])
    else:
        view_cafe = cafe.objects.all()

 
    return render(request, "Wteapp/cafe_list.html", {"cafes" : view_cafe})


def cafe_details(request : HttpRequest, cafe_id : int):

    try:
        cafes = cafe.objects.get(id=cafe_id)
        comments = CommentCafes.objects.filter(post = cafes)
    except:
        return render(request , "Wteapp/not_found.html")

    average=CommentCafes.objects.filter(post=cafes).aggregate(Avg('rating'))

    return render(request, "Wteapp/view_cafe.html", {"cafe" : cafes ,"comments" : comments , "Averages" : average})    



def add_comment(request: HttpRequest, res_id : int):


    try:
        post = restaurant.objects.get(id=res_id)
        user : User = request.user
    except:
        return render(request , "Wteapp/not_found.html")

    if not (user.is_authenticated):
        return redirect("accounts:login_user")

    if request.method == "POST":
        
        new_comment = Comment(post=post,user=user,content=request.POST["content"],rating=request.POST["rating"])
        new_comment.save()

    return redirect("Wte_app:restaurant_details", post.id)

def add_comment_cafe(request: HttpRequest, cafe_id : int):
    print("hellooooo")
    print(cafe_id)

    try:
        post = cafe.objects.get(id=cafe_id)
        user : User = request.user
    except Exception as e:
        print(e)
        return render(request , "Wteapp/not_found.html")

    if not (user.is_authenticated):
        return redirect("accounts:login_user")

    if request.method == "POST":
        
        new_comment = CommentCafes(post=post,user=user,content=request.POST["content"],rating=request.POST["rating"])
        new_comment.save()

    return redirect("Wte_app:cafe_details", post.id)   


def delete_cafe(request: HttpRequest, res_id:int):

    try:
        rest = cafe.objects.get(id=res_id)
    except:
        return render(request , "Wteapp/not_found.html")

    rest.delete()

    return redirect ("Wte_app:list_cafe")     

WTE/Wteapp/templates/Wteapp/Add_res.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Add restaurant</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  </head>
  <body>
    
    <div class="mt-5 container border rounded-3 w-50">
      <h1 class="mt-2 text-danger fst-italic">Add a new Restaurant</h1>
      <form action="{% url 'Wte_app:add_restaurant' %}" method="POST" class="d-flex flex-column gap-3" enctype="multipart/form-data">
         {% csrf_token %}
        <div class="container">

          <div class=" mt-3 row align-items-start">
            <div class="col">
              <div class="mb-3">
                <label for="exampleFormControlInput1" class="form-label">Restaurant Name:</label>
                <input name = 'name' type="text" class="form-control" id="exampleFormControlInput1" placeholder="">
              </div>   
            </div>

            <div class="col">
              <div class="mb-3">
                <label for="exampleFormControlInput1" class="form-label">City</label>
                <input name = 'city' type="text" class="form-control" id="exampleFormControlInput1" placeholder="">
              </div>
            </div>
          </div>

          <div class="row align-items-start">
            <div class="col">
              <div class="mb-3">
                <label for="exampleFormControlInput1" class="form-label">Address/Street</label>
                <input name = 'address' type="text" class="form-control" id="exampleFormControlInput1" placeholder="">
              </div>
            </div>

            <div class="col">
              <div class="mb-3">
                <label for="exampleFormControlInput1" class="form-label">Cuisine</label>
                <input name = 'Cuisine' type="text" class="form-control" id="exampleFormControlInput1" placeholder="">
              </div>
            </div>
          </div>
  
            <div class="row align-items-start">
              <div class="col">
                <div class="mb-3">
                  <label for="exampleFormControlInput1" class="form-label">Work time</label>
                  <input name = 'work_time' type="text" class="form-control" id="exampleFormControlInput1" placeholder="">
                </div>
              </div>
  
              <div class="col">
                <div class="mb-3">
                  <label for="exampleFormControlInput1" class="form-label">Menu</label>
                  <input name = 'menu' type="url" class="form-control" id="exampleFormControlInput1" placeholder="">
                </div>
              </div>
            </div>

            <div class="mb-3 row align-items-start">
              <div class="col">
                <div class="mb-3">
                  <label for="formFile" class="form-label">Upload Image:</label>
                  <input type="file" name="picture" accept="image/*" class="form-control" />
                </div>
              </div>

              <div class="col">
                <div class="mb-3">
                  <label for="exampleFormControlInput1" class="form-label">Location</label>
                  <input name='location' type="url" class="form-control" id="exampleFormControlInput1" placeholder="">
                </div>
              </div>
            </div>
            
            <div class="row align-items-start">
              <div class="col">
                <div class="mb-3">
                  <label for="exampleFormControlTextarea1" class="form-label">Description:</label>
                  <textarea name="description" class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
                </div>
              </div>
            </div>
            <div class="row align-items-start">
                <div class="col">
                  <div class="mb-3">
                    <label for="exampleFormControlInput1" class="form-label">Rating</label>
                    <input name = 'rating' type="number" class="form-control" id="exampleFormControlInput1" placeholder="">
                  </div>
                </div>
            </div>
        </div>
        <button class="m-2 btn btn-lg btn-outline-danger" type="submit">Add Restaurant</button>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>
</html>

WTE/Wteapp/templates/Wteapp/Res_list.html
{% extends 'Wteapp/base.html' %}
<title>{% block title %} Restaurant List {% endblock %} </title>

{% block content %}

<div class="row row-cols-4 ">
{% for res in restaurants %}

<div class = "col mt-2 m-5">
<div class="animate__animated animate__fadeInRight card " style="width: 18rem;">
    <img src="{{ res.picture.url }}" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">{{ res.name}}</h5>
      <p class="card-text">{{ res.description}}</p>
      <a href="{% url 'Wte_app:restaurant_details' res.id %}" class="btn btn-danger">Details</a>

      {% if request.user.is_superuser %}

      <div class="dropdown">
        <button class="btn btn-primary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          Edit
        </button>
        <ul class="dropdown-menu">
          <li><a class="dropdown-item" href="{% url 'Wte_app:delete_post' res.id %}">Delete</a></li>
        </ul>
      </div>
      {% endif  %}
    </div>

    </div>

    
</div>



{% endfor %}
</div>

{% endblock %}

WTE/Wteapp/templates/Wteapp/View_Res.html
{% extends 'Wteapp/base.html' %}

 <title>{% block title %} {{ restaurant.name }} {% endblock %} </title>

{% block content %}
<div class="position-relative">
    <img src="{{ restaurant.picture.url }}"  class="   z-index-1" style="width:100%; height:500px; object-fit: cover;"  />

    <div class="position-absolute top-0 start-0   " >
       

</div>
<div class="m-2">
<ol class="list-group list-group animate__animated animate__fadeInRight">
    <li class="list-group-item">Name: {{ restaurant.name}}</li>
    <li class="list-group-item"> City: {{ restaurant.city}}</li>
    <li class="list-group-item">Address: {{ restaurant.address}}</li>
    <li class="list-group-item">Cuisine: {{ restaurant.cuisine}}</li>
    <li class="list-group-item">Description: {{ restaurant.description}}</li>
    <li class="list-group-item">Work-time: {{ restaurant.work_time}}</li>
    <li class="list-group-item"><a href="{{ restaurant.location}}">Location</a></li>
    <li class="list-group-item"><a href="{{ restaurant.menu}}">Menu</a></li>
    <li class="list-group-item">Rating: {{ averages.rating__avg}}</li>
  
</div>


</ol>

    </div>

    <div class="container border-dark border-top" >

        <h2 >Reviews:</h2>
      
      
        {% for comment in comments %}
            <div class="border rounded-4 p-3 mt-2 bg-white">
              <span>{{ comment.user.username }}</span>
              <p>{{comment.created_at}}</p>

              <hr>
              <p>{{ comment.content }}</p>
              <p>{{ comment.rating }}</p>

            </div>
        {% endfor %}
      
        <hr/>
        <form action="{% url 'Wte_app:comment' restaurant.id %}" method="POST"  enctype="multipart/form-data">
            {% csrf_token %}
            <label class="form-label "><b>Reviews:</b></label>
            <textarea name="content" class="form-control"></textarea>
            <label for="customRange3" class="form-label"><b> rate the restaurant:</b></label>
            <input type="range" class="form-range" min="0" max="5" step="0.5" id="customRange3" name="rating" />
            <input type="submit" class="btn btn-outline-dark mt-3" value="New Reviews" />
            
        </form>
      
      </div>
    
    








{% endblock %}

WTE/Wteapp/templates/Wteapp/View_cafe.html
{% extends 'Wteapp/base.html' %}

<title>{% block title %} {{ cafe.name }} {% endblock %} </title>

{% block content %}
<div class="position-relative">
    <img src="{{ cafe.picture.url }}"  class="   z-index-1" style="width:100%; height:500px; object-fit: cover;"  />

    <div class="position-absolute top-0 start-0   " >
        

</div>
<div class="m-2 ">
<ol class="list-group list-group animate__animated animate__fadeInRight ">
    <li class="list-group-item">Name: {{ cafe.name}}</li>
    <li class="list-group-item">City: {{ cafe.city}}</li>
    <li class="list-group-item">Address: {{ cafe.address}}</li>
    <li class="list-group-item">Cuisine: {{ cafe.cuisine}}</li>
    <li class="list-group-item">Description: {{ cafe.description}}</li>
    <li class="list-group-item">Work-time: {{ cafe.work_time}}</li>
    <li class="list-group-item"><a href="{{ cafe.location}}">Location</a></li>
    <li class="list-group-item"><a href="{{ cafe.menu}}">Menu</a></li>
    <li class="list-group-item">Rating: {{ Averages.rating__avg}} </li>
</div>


</ol>
    </div>
    <div class="container border-dark border-top" >

        <h2 >Reviews :</h2>
      
      
        {% for comment in comments %}
            <div class=" border rounded-4 p-3 mt-2 bg-white">
              <span>{{ comment.user.username }}</span>
              <p>{{comment.created_at}}</p>

              <hr>
              <p>{{ comment.content }}</p>
              <p>{{ comment.rating }}</p>
            </div>
        {% endfor %}
      
        <hr/>
        
        <form action="{% url 'Wte_app:comments' cafe.id %}" method="POST" >
            {% csrf_token %}
            <label class="form-label "><b>Reviews:</b></label>
            <textarea name="content" class="form-control"></textarea>
            <label for="customRange3" class="form-label"><b> rate the restaurant:</b></label>
            <input type="range" class="form-range" min="0" max="5" step="0.5" id="customRange3" name="rating" />
            <input type="submit" class="btn btn-outline-dark mt-3" value="New Reviews" />
            
        </form>
      
      </div>
    
    
    {% endblock %}

WTE/Wteapp/templates/Wteapp/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} Where-to-eat {% endblock %} </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
  />
  <style>
    .carousel-img{
      border-radius: 10px;

    }
  </style>
  </head>

  <body style="background: rgb(251,223,63);
  background: radial-gradient(circle, rgba(251,223,63,1) 0%, rgba(252,70,70,1) 78%);">
    

    <nav class="py-2  border-bottom  border-dark "   >
      <div class="container d-flex flex-wrap ">
        <ul class="nav me-auto">
          <li class="nav-item "><a href="{% url 'Wte_app:list_restaurant' %}" class="nav-link link-dark px-2 active" aria-current="page">Restaurants</a></li>
          <li class="nav-item"><a href="{% url 'Wte_app:list_cafe' %}" class="nav-link link-dark px-2">Cafes</a></li>
          <li class="nav-item"><a href="#" class="nav-link link-dark px-2">FAQs</a></li>
          <li class="nav-item"><a href="#" class="nav-link link-dark px-2">About</a></li>
          {% if request.user.is_superuser %}
          <li class="nav-item"><a href="{% url 'Wte_app:add_restaurant' %}" class="nav-link link-dark px-2">Add restaurant</a></li>
          <li class="nav-item"><a href="{% url 'Wte_app:add_cafe' %}" class="nav-link link-dark px-2">Add Cafe</a></li>
            {% endif %}
        </ul>
        <ul class="nav"  >
          {% if request.user.is_authenticated %}
          <strong class="text-dark nav-link">Welcome {{ request.user.first_name }}</strong>

          <li class="nav-item"><a href="{% url 'accounts:logout_user' %}" class="nav-link link-dark px-2">Logout</a></li>
          {% else %}

          <li class="nav-item"><a href="{% url 'accounts:login_user' %}" class="nav-link link-dark px-2">Login</a></li>
          <li class="nav-item"><a href="{% url 'accounts:register_user' %}" class="nav-link link-dark px-2">Sign up</a></li>
          {% endif %}

        </ul>
      </div>
    </nav>
    <header class="py-3 mb-4 border-bottom  border-dark ">
      <div class="container d-flex flex-wrap justify-content-center">
        <a href="{% url 'Wte_app:HomePage' %}" class="d-flex align-items-center mb-3 mb-lg-0 me-lg-auto text-dark text-decoration-none">
          <svg class="bi me-2" width="40" height="32"><use xlink:href=""/></svg>
          <span class="fs-4" >Where-to-eat</span>
        </a>
        <form class="col-12 col-lg-auto mb-3 mb-lg-0" role="search" action="{% url 'Wte_app:list_restaurant' %}">
          <input type="search" class="form-control" name="search" placeholder="Search..." aria-label="Search">
        </form>
      </div>
    </header>
    
    {% block content %}
    <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel" style="  width:100%; height:500px;" >
        <div class="carousel-inner">
            
          <div class="carousel-item active " style="width:100%; height:500px; object-fit: cover;">
            
            <img src="{% static 'images/WTE1.jpg'%}" class="d-block w-100" alt="..."  >
            <div class="carousel-caption d-none d-md-block text-danger ">
                <h1>Ernestine Ulmer                </h1>
                <p>"Life is uncertain. Eat dessert first."</p>
              </div>
            
          </div>
          <div class="carousel-item " style="width:100%; height:500px; object-fit: cover;">
            <img src="{% static 'images/WTE2.jpg'%}" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block text-danger ">
                <h1>John Gunther</h1>
                <p>"All happiness depends on a leisurely breakfast."</p>
              </div>
          </div>
          <div class="carousel-item" style="width:100%; height:500px; object-fit: cover;">
            <img src="{% static 'images/WTE3.jpg'%}" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block text-danger  ">
                <h1 >Thomas Keller</h1>
                <p>"A recipe has no soul. You, as the cook, must bring soul to the recipe." </p>
              </div>
          </div>
        </div>
      </div>
        </div>
        {% endblock %}
      
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    
      </div>
  </body>
  <footer class="container-md d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top border-dark">
    <div class="col-md-4 d-flex align-items-center">
      <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
        <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
      </a>
      <span class="mb-3 mb-md-0 text-dark">© 2022 Where-to-eat, Inc</span>
    </div>

    <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-twitter me-2" viewBox="0 0 16 16">
            <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/>
          </svg>
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-linkedin me-2" viewBox="0 0 16 16">
            <path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854V1.146zm4.943 12.248V6.169H2.542v7.225h2.401zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248-.822 0-1.359.54-1.359 1.248 0 .694.521 1.248 1.327 1.248h.016zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016a5.54 5.54 0 0 1 .016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225h2.4z"/>
          </svg>      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-github me-2" viewBox="0 0 16 16">
            <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"/>
          </svg>
    </ul>
  </footer>
</html>

WTE/Wteapp/templates/Wteapp/cafe_list.html
{% extends 'Wteapp/base.html' %}
<title>{% block title %} Cafe List {% endblock %} </title>

{% block content %}

<div class="row row-cols-4 ">
  {% for res in cafes %}
  
  <div class = "col mt-2 m-5">
  <div class="animate__animated animate__fadeInRight card " style="width: 18rem;">
      <img src="{{ res.picture.url }}" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">{{ res.name}}</h5>
        <p class="card-text">{{ res.description}}</p>
        <a href="{% url 'Wte_app:cafe_details' res.id %}" class="btn btn-danger">Details</a>
  
        {% if request.user.is_superuser %}
  
        <div class="dropdown">
          <button class="btn btn-primary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            Edit
          </button>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'Wte_app:delete_cafe' res.id %}">Delete</a></li>
          </ul>
        </div>
        {% endif  %}
      </div>
  
      </div>
  
      
  </div>
  
  
  
  {% endfor %}
  </div>
  
  {% endblock %}
  

WTE/Wteapp/templates/Wteapp/not_found.html
{% extends 'Wteapp/base.html' %}
{% load static %}
{% block title %} Error 404 {% endblock %}

{% block content %}
<div class="container" >
<img src="{% static 'images/error_4044.jpg'%}"   alt="" style="width:100%; height:500px; object-fit: cover;">
</div>

{% endblock %}