WTE/WTE/urls.py
from django.contrib import admin
from django.urls import path,include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Wteapp.urls')),
    path('accounts/', include("accounts.urls")),
    

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

WTE/Wteapp/urls.py
from django.urls import path

from . import views



app_name = 'Wte_app'


urlpatterns = [
    path ('home/',views.home_Page,name='HomePage'),
    path("restaurant/add/", views.add_restaurant, name="add_restaurant"),
    path("restaurant/list/", views.list_restaurant, name="list_restaurant"),
    path("restaurant/detail/<res_id>/", views.restaurant_details, name="restaurant_details"),
    path("restaurant/delete/<res_id>/", views.delete_post, name="delete_post"),
    path("cafe/delete/<res_id>/", views.delete_cafe, name="delete_cafe"),
    path("cafe/add/", views.add_cafe, name="add_cafe"),
    path("cafe/list/", views.list_cafe, name="list_cafe"),
    path("cafe/detail/<cafe_id>/", views.cafe_details, name="cafe_details"),
    path("comment/<res_id>/", views.add_comment, name="comment"),
    path("comment/cafe/<cafe_id>/", views.add_comment_cafe, name="comments"),





]

WTE/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("register/", views.register_user, name="register_user"),
    path("login/", views.login_user, name="login_user"),
    path("logout/", views.logout_user, name="logout_user")
]

WTE/accounts/models.py
from django.db import models

# Create your models here.

WTE/accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout

# Create your views here.

def register_user(request : HttpRequest):

    if request.method == "POST":

        new_user = User.objects.create_user(username=request.POST["username"], email= request.POST["email"], first_name=request.POST["first_name"], last_name=request.POST["last_name"], password=request.POST["password"])
        new_user.save()
        return redirect ("Wte_app:HomePage")
    return render(request, "accounts/register.html")


def login_user(request : HttpRequest):
    msg = ""
    if request.method == "POST":
        user = authenticate(request, username=request.POST["username"], password=request.POST["password"])
        
        if user:
            login(request, user)
            return redirect("Wte_app:HomePage")
        else:
            msg = "User Not Found , check your credentials"

    return render(request, "accounts/login.html", {"msg" : msg})


def logout_user(request: HttpRequest):

    logout(request)

    return redirect("Wte_app:HomePage")

    

WTE/accounts/templates/accounts/login.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.104.2">
    <title>Signin Template · Bootstrap v5.2</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/sign-in/">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">


    

    

<link href="/docs/5.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.2/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.2/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.2/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.2/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.2/assets/img/favicons/safari-pinned-tab.svg" color="#712cf9">
<link rel="icon" href="/docs/5.2/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#712cf9">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
    </style>

    
    <!-- Custom styles for this template -->
    <div class="container w-50  border mt-5 border-dark" style="width: 100px;" >
    <link href="signin.css" rel="stylesheet">
  </head>
  
  <body  class="text-center" style="background: rgb(251,223,63);
  background: radial-gradient(circle, rgba(251,223,63,1) 0%, rgba(252,70,70,1) 78%);">
    
<main class="form-signin w-50 m-auto  ">
  <form action="{% url 'accounts:login_user' %}" method="POST">
    {% csrf_token %}
    <strong class="">{{ msg }}</strong>

    <a href="{% url 'Wte_app:HomePage' %}"><img class="mb-4 mt-2 rounded-3" src="{% static 'images/Where-To-Eat.png'%}" alt="" width="100" height="100" > </a>
    <h1 class="h3 mb-3 fw-normal fst-italic text-danger">Please sign in</h1>

    <div class="form-floating ">
      <input name ="username" type="text" class="form-control fst-italic text-danger  " id="floatingInput" placeholder="username">
      <label for="floatingInput" class="fst-italic text-danger ">username</label>
    </div>
    <div class="form-floating">
      <input name="password" type="password" class="form-control " id="floatingPassword" placeholder="Password">
      <label for="floatingPassword" class="fst-italic text-danger ">Password</label>
    </div>

    <div class="checkbox mb-3 fst-italic">
      <label>
        <input type="checkbox" value="remember-me" > Remember me
      </label>
    </div>
    <button class="w-100 btn btn-lg btn-danger fst-italic" type="submit">Sign in</button>
    <p class="mt-5 mb-3 text-muted">&copy; 2017–2022</p>
  </form>
</main>
</div>

    
  </body>
</html>

WTE/accounts/templates/accounts/register.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
<body style="background: rgb(251,223,63);
background: radial-gradient(circle, rgba(251,223,63,1) 0%, rgba(252,70,70,1) 78%);">
    

<title>Register</title>
<div class="bg-">
    <div class="container w-50 border mt-3 mb-5 border-dark">
    
        <h1><p class="text-center fst-italic text-danger">Where-To-Eat</p></h1>
        
    
        <form action="{% url 'accounts:register_user' %}" method="POST" class="d-flex flex-column gap-3">
           {% csrf_token %}
            <h2></h2>
            <h1 class="h3 mb-3 fw-normal fst-italic text-danger">Create an account </h1>
        
            <div class="form-floating">
                <input type="text" class="form-control" id="floatingInput" placeholder="username " name="username">
                <label for="floatingInput" class="fst-italic text-danger">User Name</label>
              </div>
    
              <div class="form-floating">
                <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com" name="email">
                <label for="floatingInput" class="fst-italic text-danger">Email address</label>
              </div>
    
              <div class="form-floating">
                <input type="text" class="form-control" id="floatingInput" placeholder="First Name" name="first_name">
                <label for="floatingInput" class="fst-italic text-danger">First Name</label>
              </div>
    
              <div class="form-floating">
                <input type="text" class="form-control" id="floatingInput" placeholder="Last Name" name="last_name">
                <label for="floatingInput" class="fst-italic text-danger">Last Name</label>
              </div>
    
    
            <div class="form-floating">
              <input type="password" class="form-control" id="floatingPassword" placeholder="Password" name="password">
              <label for="floatingPassword" class="fst-italic text-danger">Password</label>
            </div>
    
        
            <button class="w-100 btn btn-lg btn-danger fst-italic" type="submit">Sign in</button>
            <p class="mt-5 mb-3 text-danger border-top border-dark ">© 2017-2022</p>
            
          </form>
    
    
    </div>
    
    
    
</div>
</body>